# Generated by Django 3.2.9 on 2021-11-30 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название аранжировки')),
                ('tempo', models.IntegerField(default='100', verbose_name='темп')),
                ('original_name', models.CharField(blank=True, max_length=128, verbose_name='оригинальное название')),
                ('cover', models.ImageField(upload_to='cover', verbose_name='изображение')),
                ('audioFile', models.FileField(upload_to='audio', verbose_name='аудиозапись')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена')),
                ('date', models.DateField(auto_now=True)),
                ('archive', models.FileField(upload_to='archive_project', verbose_name='Архив с проектом')),
                ('is_buy', models.BooleanField(default=False, verbose_name='куплена')),
            ],
            options={
                'verbose_name': 'аранжировка',
                'verbose_name_plural': 'аранжировки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='Тональность')),
            ],
            options={
                'verbose_name': 'тональность',
                'verbose_name_plural': 'тональность',
            },
        ),
        migrations.CreateModel(
            name='UserArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения товара')),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.arrangement', verbose_name='аранжировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'куплено',
                'verbose_name_plural': 'куплены',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен')], default='new', max_length=100, verbose_name='Статус заказ')),
                ('form_order', models.CharField(max_length=128, verbose_name='форма оплаты')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения заказа')),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.arrangement', verbose_name='аранжировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AddField(
            model_name='arrangement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.key', verbose_name='тональность'),
        ),
    ]
