# Generated by Django 3.2.9 on 2021-11-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='text',
            field=models.TextField(blank=True, verbose_name='текст песни'),
        ),
    ]
