# Generated by Django 3.2.9 on 2021-12-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_arrangement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
