# Generated by Django 3.2.9 on 2021-12-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_arrangement_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='is_buy',
        ),
    ]
