# Generated by Django 3.2.9 on 2021-12-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_arrangement_is_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('messages', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'поддержка',
                'verbose_name_plural': 'поддержка',
            },
        ),
    ]
