# Generated by Django 3.2 on 2022-04-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangement',
            options={'ordering': ['-date'], 'verbose_name': 'аранжировку', 'verbose_name_plural': 'аранжировки'},
        ),
    ]
