# Generated by Django 3.2 on 2022-05-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_arrangement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
