# Generated by Django 3.2 on 2022-05-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_arrangement_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='slug',
        ),
    ]
