# Generated by Django 3.2.9 on 2021-11-30 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basketapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbasket',
            name='arrangement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.arrangement', verbose_name='аранжировка'),
        ),
        migrations.AddField(
            model_name='cartbasket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
